name: Update Formula

on:
  repository_dispatch:
    types: [update_formula]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Calculate SHA256 for Darwin ARM64
        run: |
          curl -L "https://github.com/antnsn/BastionBuddy/releases/download/v${{ github.event.client_payload.version }}/bastionbuddy_${{ github.event.client_payload.version }}_darwin_arm64.tar.gz" -o darwin_arm64.tar.gz
          echo "darwin_arm64_sha=$(sha256sum darwin_arm64.tar.gz | cut -d ' ' -f 1)" >> $GITHUB_ENV

      - name: Calculate SHA256 for Darwin AMD64
        run: |
          curl -L "https://github.com/antnsn/BastionBuddy/releases/download/v${{ github.event.client_payload.version }}/bastionbuddy_${{ github.event.client_payload.version }}_darwin_amd64.tar.gz" -o darwin_amd64.tar.gz
          echo "darwin_amd64_sha=$(sha256sum darwin_amd64.tar.gz | cut -d ' ' -f 1)" >> $GITHUB_ENV

      - name: Calculate SHA256 for Linux ARM64
        run: |
          curl -L "https://github.com/antnsn/BastionBuddy/releases/download/v${{ github.event.client_payload.version }}/bastionbuddy_${{ github.event.client_payload.version }}_linux_arm64.tar.gz" -o linux_arm64.tar.gz
          echo "linux_arm64_sha=$(sha256sum linux_arm64.tar.gz | cut -d ' ' -f 1)" >> $GITHUB_ENV

      - name: Calculate SHA256 for Linux AMD64
        run: |
          curl -L "https://github.com/antnsn/BastionBuddy/releases/download/v${{ github.event.client_payload.version }}/bastionbuddy_${{ github.event.client_payload.version }}_linux_amd64.tar.gz" -o linux_amd64.tar.gz
          echo "linux_amd64_sha=$(sha256sum linux_amd64.tar.gz | cut -d ' ' -f 1)" >> $GITHUB_ENV

      - name: Update Formula
        run: |
          cat > Formula/bastionbuddy.rb << EOL
          class Bastionbuddy < Formula
            desc "CLI tool for managing Azure Bastion connections"
            homepage "https://github.com/antnsn/BastionBuddy"
            version "${{ github.event.client_payload.version }}"

            on_macos do
              if Hardware::CPU.arm?
                url "https://github.com/antnsn/BastionBuddy/releases/download/v#{version}/bastionbuddy_#{version}_darwin_arm64.tar.gz"
                sha256 "${{ env.darwin_arm64_sha }}"
              else
                url "https://github.com/antnsn/BastionBuddy/releases/download/v#{version}/bastionbuddy_#{version}_darwin_amd64.tar.gz"
                sha256 "${{ env.darwin_amd64_sha }}"
              end
            end

            on_linux do
              if Hardware::CPU.arm?
                url "https://github.com/antnsn/BastionBuddy/releases/download/v#{version}/bastionbuddy_#{version}_linux_arm64.tar.gz"
                sha256 "${{ env.linux_arm64_sha }}"
              else
                url "https://github.com/antnsn/BastionBuddy/releases/download/v#{version}/bastionbuddy_#{version}_linux_amd64.tar.gz"
                sha256 "${{ env.linux_amd64_sha }}"
              end
            end

            def install
              bin.install "bastionbuddy"
            end

            test do
              system "#{bin}/bastionbuddy", "--version"
            end
          end
          EOL

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Formula/bastionbuddy.rb
          git commit -m "Update formula to version ${{ github.event.client_payload.version }}"
          git push
